### PR TITLE
Add redirectUri param to generateAuthUrl

### PR DESCRIPTION
**Pull request by asdullahsiddique**
Gives the possibility to add the `redirectUri` when calling `generateAuthUrl `

### CODE REVIEW

**Comment by lpinca** [comment]
Any reason to make this overridable? The redirect URL like the API key and the shared secret is per app so it never changes no?

**Comment by asdullahsiddique** [comment]
In my case I had to append some data via `jwt` to the ` redirectUri` after I created the `nonce`, that is the reason. I have thought that it could be to other as well.

**Comment by lpinca** [comment]
Out of curiosity, where are you adding the additional data? To the pathname?

Anyway I can't accept this as is:

- The PR is incomplete. Tests must be added and documentation updated.
- I don't like to add an additional argument to `shopifyToken.generateAuthUrl()`. There are too many arguments.  I would prefer to switch to an options object in case.

**Comment by lpinca** [comment]
Closing due to inactivity.

**Pull request closed without merging**
